
package webservice;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */

@WebService//(name = "TesteWs2Service", targetNamespace = "http://ws.jr.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WSInterface {
    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action//(input = "http://ws.jr.com/TesteWs2/sayHelloRequest", output = "http://ws.jr.com/TesteWs2/sayHelloResponse")
    public String funcService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);
    
    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action//(input = "http://ws.jr.com/TesteWs2/sayHelloRequest", output = "http://ws.jr.com/TesteWs2/sayHelloResponse")
    public String funcService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);
     
    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action//(input = "http://ws.jr.com/TesteWs2/sayHelloRequest", output = "http://ws.jr.com/TesteWs2/sayHelloResponse")
    public String funcService(
        @WebParam(name = "arg0", partName = "arg0")
        String[] arg0);
}
